---
- name: "Check Struts COUCOU"
  hosts: all
  become: yes
  remote_user: root
  gather_facts: no
  
  vars:
       script_path: /tmp/check-struts.sh
  tasks:
      #- name: "Ping hosts"
      #ping:
      
    - name: ensure a list of packages installed
      yum:
        state: present
        name: "{{ packages }}"
      vars:
        packages:
          - lsof
          - dos2unix
    - name: Upload script check-struts.sh
      copy:
        src: /home/apitcher/Documents/scripts/check_struts/check-struts.sh
        dest: "{{ script_path }}"
        mode: 00755
      changed_when: false

    - name: Check if struts presence/version
      command: "{{ script_path }}"
      register: command_result
      changed_when: "'No struts lib found' not in command_result.stdout_lines"

    - debug:
          msg: "CHECK: {{command_result}} "
      when: command_result.changed
   
    - name: Remove check-struts.sh
      file:
        dest: "{{ script_path }}"
        state: absent
      changed_when: false
